"""add color_acento to users

Revision ID: 0050b49702a9
Revises: bbb26153514e
Create Date: 2026-08-18 23:45:44.321051

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision = '0050b49702a9'
down_revision = 'bbb26153514e'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('color_acento', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'color_acento')
    # ### end Alembic commands ###
