"""add dia_vencimiento to concepts

Revision ID: 0766c5016ecf
Revises: ac73ccacca1c
Create Date: 2026-08-16 04:28:01.371334

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision = '0766c5016ecf'
down_revision = 'ac73ccacca1c'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('concepts', sa.Column('dia_vencimiento', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('concepts', 'dia_vencimiento')
    # ### end Alembic commands ###
