"""add ics_token to users

Revision ID: 07f21cce600a
Revises: 08baf805ac6d
Create Date: 2026-09-03 23:28:42.531909

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision = '07f21cce600a'
down_revision = '08baf805ac6d'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('ics_token', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.create_index(op.f('ix_users_ics_token'), 'users', ['ics_token'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_ics_token'), table_name='users')
    op.drop_column('users', 'ics_token')
    # ### end Alembic commands ###
