"""remove saldo disponible from users

Revision ID: 08baf805ac6d
Revises: 765b01aad959
Create Date: 2026-08-28 03:45:20.149440

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision = '08baf805ac6d'
down_revision = '765b01aad959'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'saldo_disponible_inicial')
    op.drop_column('users', 'saldo_disponible_fecha')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('saldo_disponible_fecha', sa.DATE(), autoincrement=False, nullable=True))
    op.add_column('users', sa.Column('saldo_disponible_inicial', sa.NUMERIC(precision=14, scale=2), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
