"""add interes to abonos

Revision ID: 462903fb7ee3
Revises: fbda4d671deb
Create Date: 2026-08-27 18:49:35.510954

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision = '462903fb7ee3'
down_revision = 'fbda4d671deb'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('abonos', sa.Column('interes', sa.Numeric(precision=14, scale=2), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('abonos', 'interes')
    # ### end Alembic commands ###
