"""add deudor amortization and cuota_deudor

Revision ID: 669566865f77
Revises: 07f21cce600a
Create Date: 2026-09-05 17:06:13.602679

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision = '669566865f77'
down_revision = '07f21cce600a'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # periodotasa enum already exists (created for concepts.periodo_tasa in
    # cb1ec443a112) - reuse it, don't recreate.
    periodo_tasa_enum = sa.Enum('MENSUAL', 'ANUAL', name='periodotasa', create_type=False)
    op.create_table('cuotas_deudor',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('deudor_id', sa.Integer(), nullable=False),
    sa.Column('anio', sa.Integer(), nullable=False),
    sa.Column('mes', sa.Integer(), nullable=False),
    sa.Column('monto_planeado', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('monto_pagado', sa.Numeric(precision=14, scale=2), nullable=True),
    sa.Column('pagado', sa.Boolean(), nullable=False),
    sa.Column('fecha_pago', sa.Date(), nullable=True),
    sa.Column('interes', sa.Numeric(precision=14, scale=2), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['deudor_id'], ['deudores.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('deudor_id', 'anio', 'mes', name='uq_cuota_deudor_anio_mes')
    )
    op.create_index(op.f('ix_cuotas_deudor_deudor_id'), 'cuotas_deudor', ['deudor_id'], unique=False)
    op.add_column('deudores', sa.Column('tasa_interes', sa.Numeric(precision=7, scale=4), nullable=True))
    op.add_column('deudores', sa.Column('periodo_tasa', periodo_tasa_enum, nullable=True))
    op.add_column('deudores', sa.Column('numero_cuotas', sa.Integer(), nullable=True))
    op.add_column('deudores', sa.Column('cuota_inicial', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('deudores', 'cuota_inicial')
    op.drop_column('deudores', 'numero_cuotas')
    op.drop_column('deudores', 'periodo_tasa')
    op.drop_column('deudores', 'tasa_interes')
    op.drop_index(op.f('ix_cuotas_deudor_deudor_id'), table_name='cuotas_deudor')
    op.drop_table('cuotas_deudor')
    # Not dropping the periodotasa enum type - still used by concepts.periodo_tasa.
    # ### end Alembic commands ###
