"""add abonos_capital_conceptos table

Revision ID: 6c54ef65366f
Revises: 7b2ca1c6fce0
Create Date: 2026-09-23 17:03:33.105837

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision = '6c54ef65366f'
down_revision = '7b2ca1c6fce0'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('abonos_capital_conceptos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('concepto_id', sa.Integer(), nullable=False),
    sa.Column('monto', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('fecha', sa.Date(), nullable=False),
    sa.ForeignKeyConstraint(['concepto_id'], ['concepts.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_abonos_capital_conceptos_concepto_id'), 'abonos_capital_conceptos', ['concepto_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_abonos_capital_conceptos_concepto_id'), table_name='abonos_capital_conceptos')
    op.drop_table('abonos_capital_conceptos')
    # ### end Alembic commands ###
