"""add ahorros and saldo disponible to users

Revision ID: 765b01aad959
Revises: 462903fb7ee3
Create Date: 2026-08-27 19:00:23.991071

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision = '765b01aad959'
down_revision = '462903fb7ee3'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('ahorros', sa.Numeric(precision=14, scale=2), nullable=True))
    op.add_column('users', sa.Column('saldo_disponible_inicial', sa.Numeric(precision=14, scale=2), nullable=True))
    op.add_column('users', sa.Column('saldo_disponible_fecha', sa.Date(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'saldo_disponible_fecha')
    op.drop_column('users', 'saldo_disponible_inicial')
    op.drop_column('users', 'ahorros')
    # ### end Alembic commands ###
