"""add es_abono_capital to abonos

Revision ID: 7b2ca1c6fce0
Revises: e87a6ae30f73
Create Date: 2026-09-05 20:04:50.759928

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision = '7b2ca1c6fce0'
down_revision = 'e87a6ae30f73'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        'abonos',
        sa.Column('es_abono_capital', sa.Boolean(), nullable=False, server_default=sa.false()),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('abonos', 'es_abono_capital')
    # ### end Alembic commands ###
