"""add whatsapp linking and pending session

Revision ID: 9b1c76d1d924
Revises: 6c54ef65366f
Create Date: 2026-09-23 18:57:19.341360

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision = '9b1c76d1d924'
down_revision = '6c54ef65366f'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('whatsapp_sessions',
    sa.Column('phone_number', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('pending_response_json', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('pending_original_message', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('expires_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('phone_number')
    )
    op.add_column('users', sa.Column('whatsapp_phone', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('users', sa.Column('whatsapp_link_token', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.create_index(op.f('ix_users_whatsapp_link_token'), 'users', ['whatsapp_link_token'], unique=True)
    op.create_index(op.f('ix_users_whatsapp_phone'), 'users', ['whatsapp_phone'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_whatsapp_phone'), table_name='users')
    op.drop_index(op.f('ix_users_whatsapp_link_token'), table_name='users')
    op.drop_column('users', 'whatsapp_link_token')
    op.drop_column('users', 'whatsapp_phone')
    op.drop_table('whatsapp_sessions')
    # ### end Alembic commands ###
