"""add duracion_meses to concepts

Revision ID: ac73ccacca1c
Revises: cb1ec443a112
Create Date: 2026-08-15 22:33:01.467530

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision = 'ac73ccacca1c'
down_revision = 'cb1ec443a112'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('concepts', sa.Column('duracion_meses', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('concepts', 'duracion_meses')
    # ### end Alembic commands ###
