"""add gastos and gasto_categoria

Revision ID: bbb26153514e
Revises: 65ec3e67a79a
Create Date: 2026-08-18 22:43:32.748331

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision = 'bbb26153514e'
down_revision = '65ec3e67a79a'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('gastos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('monto', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('fecha', sa.Date(), nullable=False),
    sa.Column('descripcion', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_gastos_user_id'), 'gastos', ['user_id'], unique=False)
    op.create_table('gasto_categoria',
    sa.Column('gasto_id', sa.Integer(), nullable=False),
    sa.Column('categoria_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['categoria_id'], ['categorias.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['gasto_id'], ['gastos.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('gasto_id', 'categoria_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('gasto_categoria')
    op.drop_index(op.f('ix_gastos_user_id'), table_name='gastos')
    op.drop_table('gastos')
    # ### end Alembic commands ###
