"""add debt amortization fields

Revision ID: cb1ec443a112
Revises: f115d9370a4b
Create Date: 2026-08-15 22:02:58.979173

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision = 'cb1ec443a112'
down_revision = 'f115d9370a4b'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    periodo_tasa_enum = sa.Enum('MENSUAL', 'ANUAL', name='periodotasa')
    periodo_tasa_enum.create(op.get_bind(), checkfirst=True)
    op.add_column('concepts', sa.Column('tasa_interes', sa.Numeric(precision=7, scale=4), nullable=True))
    op.add_column('concepts', sa.Column('periodo_tasa', periodo_tasa_enum, nullable=True))
    op.add_column('concepts', sa.Column('numero_cuotas', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('concepts', 'numero_cuotas')
    op.drop_column('concepts', 'periodo_tasa')
    op.drop_column('concepts', 'tasa_interes')
    sa.Enum(name='periodotasa').drop(op.get_bind(), checkfirst=True)
    # ### end Alembic commands ###
