"""make google_sub nullable, add password_hash to users

Revision ID: e614567d3cf1
Revises: 0766c5016ecf
Create Date: 2026-08-16 04:53:17.452819

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision = 'e614567d3cf1'
down_revision = '0766c5016ecf'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('password_hash', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.alter_column('users', 'google_sub',
               existing_type=sa.VARCHAR(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'google_sub',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.drop_column('users', 'password_hash')
    # ### end Alembic commands ###
