"""add savings ledger, drop users.ahorros

Revision ID: e87a6ae30f73
Revises: 669566865f77
Create Date: 2026-09-05 17:27:29.365872

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision = 'e87a6ae30f73'
down_revision = '669566865f77'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('aportes_ahorro',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('monto', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('tipo', sa.Enum('APORTE', 'RETIRO', name='tipoaporte'), nullable=False),
    sa.Column('fecha', sa.Date(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_aportes_ahorro_user_id'), 'aportes_ahorro', ['user_id'], unique=False)
    # Data migration: every user's existing non-null ahorros value becomes
    # their first ledger entry, dated today, before the column is dropped.
    op.execute(
        """
        INSERT INTO aportes_ahorro (user_id, monto, tipo, fecha, created_at)
        SELECT id, ahorros, 'APORTE', CURRENT_DATE, NOW()
        FROM users
        WHERE ahorros IS NOT NULL
        """
    )
    op.drop_column('users', 'ahorros')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('ahorros', sa.NUMERIC(precision=14, scale=2), autoincrement=False, nullable=True))
    # Best-effort, lossy backfill from the computed ledger balance - see
    # design.md. Individual entries and their dates are not recoverable.
    op.execute(
        """
        UPDATE users u
        SET ahorros = COALESCE((
            SELECT SUM(CASE WHEN a.tipo = 'APORTE' THEN a.monto ELSE -a.monto END)
            FROM aportes_ahorro a
            WHERE a.user_id = u.id
        ), NULL)
        """
    )
    op.drop_index(op.f('ix_aportes_ahorro_user_id'), table_name='aportes_ahorro')
    op.drop_table('aportes_ahorro')
    sa.Enum(name='tipoaporte').drop(op.get_bind(), checkfirst=True)
    # ### end Alembic commands ###
