"""cascade delete monthly entries with concept

Revision ID: f115d9370a4b
Revises: 7d187ae6d3a9
Create Date: 2026-08-15 20:53:42.680400

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision = 'f115d9370a4b'
down_revision = '7d187ae6d3a9'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('monthly_entries_concepto_id_fkey'), 'monthly_entries', type_='foreignkey')
    op.create_foreign_key(None, 'monthly_entries', 'concepts', ['concepto_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'monthly_entries', type_='foreignkey')
    op.create_foreign_key(op.f('monthly_entries_concepto_id_fkey'), 'monthly_entries', 'concepts', ['concepto_id'], ['id'])
    # ### end Alembic commands ###
