"""add cuota_inicial to concepts

Revision ID: f42535b07c6b
Revises: e614567d3cf1
Create Date: 2026-08-17 21:09:10.483864

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision = 'f42535b07c6b'
down_revision = 'e614567d3cf1'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('concepts', sa.Column('cuota_inicial', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('concepts', 'cuota_inicial')
    # ### end Alembic commands ###
