"""add categorias and concepto_categoria

Revision ID: f9964a7633d3
Revises: f42535b07c6b
Create Date: 2026-08-18 17:24:56.430018

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision = 'f9964a7633d3'
down_revision = 'f42535b07c6b'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('categorias',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('nombre', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('emoji', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_categorias_user_id'), 'categorias', ['user_id'], unique=False)
    op.create_table('concepto_categoria',
    sa.Column('concepto_id', sa.Integer(), nullable=False),
    sa.Column('categoria_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['categoria_id'], ['categorias.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['concepto_id'], ['concepts.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('concepto_id', 'categoria_id')
    )
    # ### end Alembic commands ###

    # Data migration: one Categoria per distinct (user_id, categoria) string
    # still in use, linked to every concept that had it - see
    # add-categories/design.md for why this runs as raw SQL here rather than
    # importing the SQLModel classes.
    bind = op.get_bind()
    distinct_categorias = bind.execute(
        sa.text("SELECT DISTINCT user_id, categoria FROM concepts WHERE categoria IS NOT NULL")
    ).fetchall()
    for user_id, nombre in distinct_categorias:
        categoria_id = bind.execute(
            sa.text(
                "INSERT INTO categorias (user_id, nombre, created_at) "
                "VALUES (:user_id, :nombre, now()) RETURNING id"
            ),
            {"user_id": user_id, "nombre": nombre},
        ).scalar_one()
        bind.execute(
            sa.text(
                "INSERT INTO concepto_categoria (concepto_id, categoria_id) "
                "SELECT id, :categoria_id FROM concepts "
                "WHERE user_id = :user_id AND categoria = :nombre"
            ),
            {"categoria_id": categoria_id, "user_id": user_id, "nombre": nombre},
        )

    op.drop_column('concepts', 'categoria')


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('concepts', sa.Column('categoria', sa.VARCHAR(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###

    # Best-effort data backfill: a concept that ends up with zero or many
    # linked categories cannot be losslessly reduced to one string, so this
    # arbitrarily picks the lowest categoria_id among its assigned categories
    # (or leaves categoria NULL if it had none) - see design.md's Risks
    # section for why this gap is accepted rather than engineered around.
    bind = op.get_bind()
    bind.execute(
        sa.text(
            """
            UPDATE concepts
            SET categoria = sub.nombre
            FROM (
                SELECT DISTINCT ON (cc.concepto_id) cc.concepto_id, cat.nombre
                FROM concepto_categoria cc
                JOIN categorias cat ON cat.id = cc.categoria_id
                ORDER BY cc.concepto_id, cc.categoria_id
            ) AS sub
            WHERE concepts.id = sub.concepto_id
            """
        )
    )

    op.drop_table('concepto_categoria')
    op.drop_index(op.f('ix_categorias_user_id'), table_name='categorias')
    op.drop_table('categorias')
