"""add fecha_pago and finalizado_en for agenda

Revision ID: fbda4d671deb
Revises: 0050b49702a9
Create Date: 2026-08-19 00:33:23.786811

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision = 'fbda4d671deb'
down_revision = '0050b49702a9'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('concepts', sa.Column('finalizado_en', sa.Date(), nullable=True))
    op.add_column('deudores', sa.Column('finalizado_en', sa.Date(), nullable=True))
    op.add_column('monthly_entries', sa.Column('fecha_pago', sa.Date(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('monthly_entries', 'fecha_pago')
    op.drop_column('deudores', 'finalizado_en')
    op.drop_column('concepts', 'finalizado_en')
    # ### end Alembic commands ###
